# Generated by Django 5.2.17 on 2026-08-21 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен участника')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Подключился')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ('joined_at',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker_projects', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('goal', models.CharField(blank=True, max_length=500, verbose_name='Цель спринта')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Плановая ёмкость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='poker.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Спринт',
                'verbose_name_plural': 'Спринты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80, verbose_name='Номер')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('status', models.CharField(choices=[('unestimated', 'Не оценена'), ('estimated', 'Оценена')], default='unestimated', max_length=20, verbose_name='Статус')),
                ('estimate_sum', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма голосов')),
                ('estimate_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество голосов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='poker.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SprintTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_tasks', to='poker.sprint', verbose_name='Спринт')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_items', to='poker.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Задача спринта',
                'verbose_name_plural': 'Задачи спринта',
                'ordering': ('position', 'added_at'),
            },
        ),
        migrations.AddField(
            model_name='sprint',
            name='tasks',
            field=models.ManyToManyField(related_name='sprints', through='poker.SprintTask', to='poker.task'),
        ),
        migrations.CreateModel(
            name='VotingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер раунда')),
                ('status', models.CharField(choices=[('voting', 'Голосование'), ('revealed', 'Голоса раскрыты'), ('closed', 'Оценка принята'), ('cancelled', 'Отменён')], default='voting', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Начат')),
                ('revealed_at', models.DateTimeField(blank=True, null=True, verbose_name='Раскрыт')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Принят')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_rounds', to='poker.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Раунд голосования',
                'verbose_name_plural': 'Раунды голосования',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(choices=[(0, '0'), (2, '2'), (4, '4'), (8, '8'), (12, '12'), (20, '20'), (32, '32'), (52, '52')], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Проголосовал')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменил голос')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poker.participant', verbose_name='Участник')),
                ('voting_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poker.votinground', verbose_name='Раунд')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
            },
        ),
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный токен')),
                ('status', models.CharField(choices=[('draft', 'Подготовка'), ('active', 'Идёт голосование'), ('finished', 'Завершена')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('current_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_sessions', to='poker.task', verbose_name='Текущая задача')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_sessions', to='poker.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Сессия голосования',
                'verbose_name_plural': 'Сессии голосования',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='votinground',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='poker.votingsession', verbose_name='Сессия'),
        ),
        migrations.AddField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='poker.votingsession', verbose_name='Сессия'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='unique_task_number_in_project'),
        ),
        migrations.AddConstraint(
            model_name='sprinttask',
            constraint=models.UniqueConstraint(fields=('sprint', 'task'), name='unique_task_in_sprint'),
        ),
        migrations.AddConstraint(
            model_name='sprinttask',
            constraint=models.UniqueConstraint(fields=('task',), name='task_can_belong_to_only_one_sprint'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voting_round', 'participant'), name='one_vote_per_participant_and_round'),
        ),
        migrations.AddConstraint(
            model_name='votinground',
            constraint=models.UniqueConstraint(fields=('session', 'task', 'number'), name='unique_round_number_for_task'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('session', 'name'), name='unique_participant_name_in_session'),
        ),
    ]
