# Generated by Django 5.2.17 on 2026-08-21 21:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsession',
            name='minimum_participants',
            field=models.PositiveSmallIntegerField(default=1, help_text='Сколько участников должны проголосовать до раскрытия карт.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Минимум голосов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votingsession',
            name='minimum_participants',
            field=models.PositiveSmallIntegerField(default=2, help_text='Сколько участников должны проголосовать до раскрытия карт.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Минимум голосов'),
        ),
        migrations.CreateModel(
            name='VotingSessionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Порядок')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('active', 'Оценивается'), ('completed', 'Оценена'), ('skipped', 'Пропущена')], default='pending', max_length=20, verbose_name='Статус')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Оценена')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='poker.votingsession', verbose_name='Сессия')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_queue_items', to='poker.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Задача в очереди голосования',
                'verbose_name_plural': 'Очередь голосования',
                'ordering': ('position', 'added_at'),
                'constraints': [models.UniqueConstraint(fields=('session', 'task'), name='unique_task_in_voting_queue'), models.UniqueConstraint(fields=('session', 'position'), name='unique_position_in_voting_queue')],
            },
        ),
    ]
