# Generated by Django 5.2.17 on 2026-08-21 21:45

import django.db.models.deletion
from django.db import migrations, models


def initialize_existing_rooms(apps, schema_editor):
    Participant = apps.get_model('poker', 'Participant')
    VotingRound = apps.get_model('poker', 'VotingRound')
    VotingSession = apps.get_model('poker', 'VotingSession')
    VotingSessionTask = apps.get_model('poker', 'VotingSessionTask')

    for voting_session in VotingSession.objects.all():
        queue_items = list(
            VotingSessionTask.objects.filter(session=voting_session).order_by(
                'position', 'id'
            )
        )
        first_task_id = queue_items[0].task_id if queue_items else None
        participant_task_id = voting_session.current_task_id or first_task_id
        Participant.objects.filter(
            session=voting_session, current_task__isnull=True
        ).update(current_task_id=participant_task_id)

        for queue_item in queue_items:
            latest_round = VotingRound.objects.filter(
                session=voting_session,
                task_id=queue_item.task_id,
            ).order_by('-number').first()

            if queue_item.status == 'completed':
                closed_round = VotingRound.objects.filter(
                    session=voting_session,
                    task_id=queue_item.task_id,
                    status='closed',
                ).order_by('-number').first()
                if closed_round:
                    queue_item.current_round_id = closed_round.id
                    queue_item.save(update_fields=('current_round',))
                continue

            if voting_session.status != 'active' or queue_item.status == 'skipped':
                continue

            if latest_round and latest_round.status in ('voting', 'revealed'):
                current_round = latest_round
            else:
                current_round = VotingRound.objects.create(
                    session=voting_session,
                    task_id=queue_item.task_id,
                    number=(latest_round.number if latest_round else 0) + 1,
                    status='voting',
                )
            queue_item.status = 'active'
            queue_item.current_round_id = current_round.id
            queue_item.save(update_fields=('status', 'current_round'))


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_voting_queue_and_minimum_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_cursors', to='poker.task', verbose_name='Текущая задача участника'),
        ),
        migrations.AddField(
            model_name='votingsessiontask',
            name='current_round',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_item', to='poker.votinground', verbose_name='Текущий раунд'),
        ),
        migrations.RunPython(
            initialize_existing_rooms,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
