# Generated by Django 5.2.17 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poker", "0003_asynchronous_participant_navigation"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Завершил оценку",
            ),
        ),
    ]
