# Generated by Django 5.2.17 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poker", "0004_participant_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Завершена",
            ),
        ),
        migrations.AddField(
            model_name="votingsession",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="В архиве",
            ),
        ),
        migrations.AddField(
            model_name="sprint",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Планируется"),
                    ("active", "Активен"),
                    ("completed", "Завершён"),
                ],
                default="planning",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="sprint",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="В архиве",
            ),
        ),
    ]
