# Generated by Django 5.2.17 on 2026-08-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poker", "0005_management_statuses_and_archives"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="tasks",
            field=models.ManyToManyField(
                related_name="sprints",
                through="poker.SprintTask",
                through_fields=("sprint", "task"),
                to="poker.task",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="sprinttask",
            name="task_can_belong_to_only_one_sprint",
        ),
        migrations.AddField(
            model_name="sprinttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Запланирована"),
                    ("transferred", "Перенесена"),
                ],
                default="planned",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="sprinttask",
            name="transferred_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Перенесена",
            ),
        ),
        migrations.AddField(
            model_name="sprinttask",
            name="transferred_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transferred_from_items",
                to="poker.sprint",
                verbose_name="Перенесена в спринт",
            ),
        ),
    ]
