# Generated by Django 5.2.17 on 2026-09-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0011_hour_estimation_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='task',
            name='external_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Ссылка на задачу'),
        ),
    ]
