# Generated by Django 5.2.17 on 2026-09-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0012_task_description_and_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='eva_block_reason',
            field=models.CharField(blank=True, choices=[('', 'Доступна'), ('closed', 'Закрыта или выполнена'), ('eva_assigned', 'Указан спринт EVA'), ('unestimated', 'Нет оценки EVA'), ('invalid_estimate', 'Некорректная оценка EVA')], default='', max_length=20, verbose_name='Причина недоступности по выгрузке EVA'),
        ),
        migrations.AddField(
            model_name='task',
            name='eva_sprints',
            field=models.TextField(blank=True, verbose_name='Спринты в выгрузке EVA'),
        ),
        migrations.AddField(
            model_name='task',
            name='eva_status',
            field=models.CharField(blank=True, max_length=200, verbose_name='Статус в выгрузке EVA'),
        ),
        migrations.AddField(
            model_name='task',
            name='imported_estimate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (4, '4'), (8, '8'), (12, '12'), (20, '20'), (32, '32'), (52, '52')], null=True, verbose_name='Оценка из EVA, часы'),
        ),
    ]
