# Generated by Django 5.2.17 on 2026-09-25 15:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0013_eva_sprint_planning'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='capacity_source',
            field=models.CharField(choices=[('manual', 'Ввести вручную'), ('team', 'Рассчитать по сотрудникам')], default='manual', max_length=10, verbose_name='Расчёт ёмкости'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='reserve_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Доля времени на дефекты, операционные и другие задачи вне этого плана. Вычитается один раз.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Резерв, %'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='working_days_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оставьте пустым для расчёта по пн–пт. Укажите точное число с учётом праздников и рабочих суббот.', null=True, verbose_name='Рабочих дней по календарю'),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('competency', models.CharField(choices=[('analysis', 'Аналитика'), ('development', 'Разработка'), ('testing', 'Тестирование')], max_length=20, verbose_name='Компетенция')),
                ('allocation_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Аллокация, %')),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(24)], verbose_name='Часов в день')),
                ('is_active', models.BooleanField(default=True, verbose_name='В команде')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='poker.project')),
            ],
            options={
                'verbose_name': 'Сотрудник проекта',
                'verbose_name_plural': 'Команда проекта',
                'ordering': ('full_name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='SprintResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО в спринте')),
                ('competency', models.CharField(choices=[('analysis', 'Аналитика'), ('development', 'Разработка'), ('testing', 'Тестирование')], max_length=20, verbose_name='Компетенция')),
                ('allocation_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Аллокация, %')),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(24)], verbose_name='Часов в день')),
                ('absence_days', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рабочих дней отсутствия')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_resources', to='poker.projectmember')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='poker.sprint')),
            ],
            options={
                'verbose_name': 'Сотрудник в спринте',
                'verbose_name_plural': 'Сотрудники в спринте',
                'ordering': ('full_name', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('sprint', 'member'), name='unique_member_in_sprint')],
            },
        ),
    ]
