# Generated by Django 5.2.17 on 2026-10-05 09:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0014_sprint_team_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='defect_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ёмкость дефектов, часы'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='development_abs_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ёмкость разработки АБС, часы'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='development_be_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ёмкость разработки BE, часы'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='development_fe_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ёмкость разработки FE, часы'),
        ),
        migrations.AddField(
            model_name='task',
            name='quota',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Тип квоты'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='competency',
            field=models.CharField(choices=[('analysis', 'Аналитика'), ('development', 'Разработка (не уточнена)'), ('development_abs', 'Разработка АБС'), ('development_be', 'Разработка BE'), ('development_fe', 'Разработка FE'), ('defect', 'Дефект'), ('testing', 'Тестирование')], max_length=20, verbose_name='Компетенция'),
        ),
        migrations.AlterField(
            model_name='sprintresource',
            name='competency',
            field=models.CharField(choices=[('analysis', 'Аналитика'), ('development', 'Разработка (не уточнена)'), ('development_abs', 'Разработка АБС'), ('development_be', 'Разработка BE'), ('development_fe', 'Разработка FE'), ('defect', 'Дефект'), ('testing', 'Тестирование')], max_length=20, verbose_name='Компетенция'),
        ),
        migrations.AlterField(
            model_name='sprinttask',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирована'), ('transferred', 'Перенесена'), ('removed', 'Исключена по данным EVA')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='competency',
            field=models.CharField(blank=True, choices=[('', 'Без типа'), ('analysis', 'Аналитика'), ('development', 'Разработка (не уточнена)'), ('development_abs', 'Разработка АБС'), ('development_be', 'Разработка BE'), ('development_fe', 'Разработка FE'), ('defect', 'Дефект'), ('testing', 'Тестирование')], default='', max_length=20, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='imported_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Оценка из EVA, часы'),
        ),
    ]
