# Generated by Django 5.2.17 on 2026-10-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0015_eva_sync_quotas_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='eva_readiness_stale',
            field=models.BooleanField(default=False, verbose_name='Готовность EVA требует повторного импорта'),
        ),
        migrations.AddField(
            model_name='task',
            name='eva_epic_title',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Эпик EVA'),
        ),
        migrations.AddField(
            model_name='task',
            name='eva_parent_title',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Родительская задача EVA'),
        ),
        migrations.AddField(
            model_name='task',
            name='eva_project_name',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Проект EVA'),
        ),
    ]
